"""
handler.py — Tool-Call Router & Mock Action Handlers

Receives the ``PipelineResult`` from the NLU node and dispatches
to the correct mock handler via a dispatch table.  If required fields
are missing, prompts the user instead of executing the action.

Routing flow:
  1. Check if domain/action were classified  →  fallback if not
  2. Check for missing required fields       →  prompt for them
  3. Dispatch to the appropriate mock handler

Usage:
    from src.router.handler import route
    from src.nlu.extractor import PipelineResult

    route(pipeline_result)
"""

from __future__ import annotations

import logging
from typing import Any, Callable, Dict, List, Optional

from src.nlu.extractor import PipelineResult

# ---------------------------------------------------------------------------
# Module-level logger
# ---------------------------------------------------------------------------
logger = logging.getLogger(__name__)


# ═══════════════════════════════════════════════════════════════════════════
# Mock Action Handlers — Routines
# ═══════════════════════════════════════════════════════════════════════════

def mock_create_routine(args: Dict[str, Any]) -> None:
    """Simulate creating a new health routine."""
    print("\n" + "=" * 60)
    print("✅  ACTION  ➜  CREATE ROUTINE")
    print("-" * 60)
    print(f"  Vital Test Type : {args.get('vital_test_type', '<not specified>')}")
    print(f"  Scheduled Time  : {args.get('scheduled_time', '<not specified>')}")
    print(f"  Frequency       : {args.get('frequency', '<not specified>')}")
    print(f"  Routine Name    : {args.get('routine_name', '<auto-generated>')}")
    print(f"  Notes           : {args.get('notes', '<none>')}")
    print("-" * 60)
    print("  ▸ Saving new routine to on-device scheduler …")
    print("  ▸ Confirmation sent to display.")
    print("=" * 60 + "\n")


def mock_view_routines(args: Dict[str, Any]) -> None:
    """Simulate viewing/querying routines."""
    print("\n" + "=" * 60)
    print("✅  ACTION  ➜  VIEW ROUTINES")
    print("-" * 60)
    print(f"  Category  : {args.get('category', '<all>')}")
    print(f"  Timeframe : {args.get('timeframe', '<all time>')}")
    print(f"  Frequency : {args.get('frequency', '<any>')}")
    print("-" * 60)
    print("  ▸ Querying routine database …")
    print("  ▸ Rendering routine list on-screen.")
    print("=" * 60 + "\n")


def mock_view_result(args: Dict[str, Any]) -> None:
    """Simulate viewing past vital sign readings."""
    print("\n" + "=" * 60)
    print("✅  ACTION  ➜  VIEW RESULT / READING")
    print("-" * 60)
    print(f"  Vital Type : {args.get('vital_type', '<all vitals>')}")
    print(f"  Timeframe  : {args.get('timeframe', '<most recent>')}")
    print("-" * 60)
    print("  ▸ Querying measurement history …")
    print("  ▸ Rendering results on-screen.")
    print("=" * 60 + "\n")


def mock_update_routine(args: Dict[str, Any]) -> None:
    """Simulate updating a routine."""
    print("\n" + "=" * 60)
    print("✅  ACTION  ➜  UPDATE ROUTINE")
    print("-" * 60)
    for key, val in args.items():
        print(f"  {key:18s} : {val}")
    print("-" * 60)
    print("  ▸ Updating routine in database …")
    print("  ▸ Confirmation sent to display.")
    print("=" * 60 + "\n")


def mock_delete_routine(args: Dict[str, Any]) -> None:
    """Simulate deleting a routine."""
    print("\n" + "=" * 60)
    print("✅  ACTION  ➜  DELETE ROUTINE")
    print("-" * 60)
    print(f"  Routine ID   : {args.get('routine_id', '<not specified>')}")
    print(f"  Routine Name : {args.get('routine_name', '<not specified>')}")
    print("-" * 60)
    print("  ▸ Removing routine from scheduler …")
    print("  ▸ Confirmation sent to display.")
    print("=" * 60 + "\n")


# ═══════════════════════════════════════════════════════════════════════════
# Mock Action Handlers — Profiles
# ═══════════════════════════════════════════════════════════════════════════

def mock_view_profile(args: Dict[str, Any]) -> None:
    """Simulate viewing user profile."""
    print("\n" + "=" * 60)
    print("✅  ACTION  ➜  VIEW PROFILE")
    print("-" * 60)
    print(f"  Section : {args.get('section', '<full profile>')}")
    print("-" * 60)
    print("  ▸ Loading profile from local storage …")
    print("  ▸ Rendering profile card on-screen.")
    print("=" * 60 + "\n")


def mock_update_profile(args: Dict[str, Any]) -> None:
    """Simulate updating profile fields."""
    print("\n" + "=" * 60)
    print("✅  ACTION  ➜  UPDATE PROFILE")
    print("-" * 60)
    for key, val in args.items():
        print(f"  {key:18s} : {val}")
    print("-" * 60)
    print("  ▸ Updating profile in local storage …")
    print("  ▸ Confirmation sent to display.")
    print("=" * 60 + "\n")


# ═══════════════════════════════════════════════════════════════════════════
# Mock Action Handlers — Appointments
# ═══════════════════════════════════════════════════════════════════════════

def mock_create_appointment(args: Dict[str, Any]) -> None:
    """Simulate creating an appointment."""
    print("\n" + "=" * 60)
    print("✅  ACTION  ➜  CREATE APPOINTMENT")
    print("-" * 60)
    print(f"  Doctor    : {args.get('doctor_name', '<not specified>')}")
    print(f"  Patient   : {args.get('patient_name', '<self>')}")
    print(f"  Specialty : {args.get('specialty', '<not specified>')}")
    print(f"  Date/Time : {args.get('date_time', '<not specified>')}")
    print(f"  Location  : {args.get('location', '<not specified>')}")
    print(f"  Symptoms  : {args.get('symptoms', '<none reported>')}")
    print(f"  Notes     : {args.get('notes', '<none>')}")
    print("  ▸ Saving appointment to calendar …")
    print("  ▸ Reminder set.  Confirmation sent to display.")
    print("=" * 60 + "\n")


def mock_view_appointments(args: Dict[str, Any]) -> None:
    """Simulate viewing appointments."""
    print("\n" + "=" * 60)
    print("✅  ACTION  ➜  VIEW APPOINTMENTS")
    print("-" * 60)
    print(f"  Timeframe : {args.get('timeframe', '<all>')}")
    print(f"  Doctor    : {args.get('doctor_name', '<any>')}")
    print("-" * 60)
    print("  ▸ Querying appointment calendar …")
    print("  ▸ Rendering appointment list on-screen.")
    print("=" * 60 + "\n")


def mock_cancel_appointment(args: Dict[str, Any]) -> None:
    """Simulate cancelling an appointment."""
    print("\n" + "=" * 60)
    print("✅  ACTION  ➜  CANCEL APPOINTMENT")
    print("-" * 60)
    print(f"  Appointment ID : {args.get('appointment_id', '<not specified>')}")
    print(f"  Doctor         : {args.get('doctor_name', '<not specified>')}")
    print(f"  Date/Time      : {args.get('date_time', '<not specified>')}")
    print("-" * 60)
    print("  ▸ Cancelling appointment …")
    print("  ▸ Confirmation sent to display.")
    print("=" * 60 + "\n")


# ═══════════════════════════════════════════════════════════════════════════
# Mock Action Handlers — Settings
# ═══════════════════════════════════════════════════════════════════════════

def mock_change_setting(args: Dict[str, Any]) -> None:
    """Simulate changing a setting."""
    print("\n" + "=" * 60)
    print("✅  ACTION  ➜  CHANGE SETTING")
    print("-" * 60)
    print(f"  Setting : {args.get('setting_name', '<not specified>')}")
    print(f"  Value   : {args.get('setting_value', '<not specified>')}")
    print("-" * 60)
    print("  ▸ Applying setting change …")
    print("  ▸ Confirmation sent to display.")
    print("=" * 60 + "\n")


def mock_view_settings(args: Dict[str, Any]) -> None:
    """Simulate viewing settings."""
    print("\n" + "=" * 60)
    print("✅  ACTION  ➜  VIEW SETTINGS")
    print("-" * 60)
    print(f"  Filter : {args.get('setting_name', '<all settings>')}")
    print("-" * 60)
    print("  ▸ Loading current settings …")
    print("  ▸ Rendering settings panel on-screen.")
    print("=" * 60 + "\n")


# ═══════════════════════════════════════════════════════════════════════════
# Fallback & Missing-Field Prompt
# ═══════════════════════════════════════════════════════════════════════════

def mock_fallback_prompt() -> None:
    """Prompt the user when intent is unrecognised."""
    print("\n" + "=" * 60)
    print("⚠️   FALLBACK — Intent not recognised")
    print("-" * 60)
    print('  "I didn\'t quite catch that.')
    print('   You can ask me to manage routines, view your profile,')
    print('   book appointments, or change settings."')
    print("=" * 60 + "\n")


def prompt_missing_fields(result: PipelineResult) -> None:
    """Prompt the user to provide missing required fields."""
    print("\n" + "=" * 60)
    print(f"❓  NEED MORE INFO  ➜  {result.action or 'unknown action'}")
    print("-" * 60)
    print(f"  Domain : {result.domain}")
    print(f"  Action : {result.action}")
    if result.filled_args:
        print("  Already have:")
        for k, v in result.filled_args.items():
            print(f"    ✓ {k:18s} = {v!r}")
    print("  Still need:")
    for field_name in result.missing_fields:
        # Provide friendly prompts
        friendly = field_name.replace("_", " ").title()
        print(f"    ✗ {friendly}")
    print("-" * 60)
    print('  "Could you please provide the missing information?"')
    print("=" * 60 + "\n")


# ═══════════════════════════════════════════════════════════════════════════
# Tool Dispatch Table
# ═══════════════════════════════════════════════════════════════════════════

TOOL_DISPATCH: Dict[str, Callable[[Dict[str, Any]], None]] = {
    # Routines
    "create_routine": mock_create_routine,
    "view_routines": mock_view_routines,
    "view_result": mock_view_result,
    "update_routine": mock_update_routine,
    "delete_routine": mock_delete_routine,
    # Profiles
    "view_profile": mock_view_profile,
    "update_profile": mock_update_profile,
    # Appointments
    "create_appointment": mock_create_appointment,
    "view_appointments": mock_view_appointments,
    "cancel_appointment": mock_cancel_appointment,
    # Settings
    "change_setting": mock_change_setting,
    "view_settings": mock_view_settings,
}


# ═══════════════════════════════════════════════════════════════════════════
# Route Dispatcher
# ═══════════════════════════════════════════════════════════════════════════

def route(result: PipelineResult) -> None:
    """Dispatch a PipelineResult to the correct mock handler.

    Flow:
      1. No domain/action → fallback
      2. Missing required fields → prompt user
      3. Dispatch to tool handler

    Args:
        result: The PipelineResult from IntentExtractor.analyse().
    """
    logger.info(
        "Routing  domain=%r  action=%r  filled=%s  missing=%s",
        result.domain, result.action, result.filled_args, result.missing_fields,
    )

    # --- No domain classified → fallback --------------------------------
    if result.domain is None or result.action is None:
        logger.warning("No domain/action classified — triggering fallback.")
        mock_fallback_prompt()
        return

    # --- Missing required fields → prompt user --------------------------
    if result.missing_fields:
        logger.info(
            "Missing required fields %s — prompting user.", result.missing_fields
        )
        prompt_missing_fields(result)
        return

    # --- Dispatch to tool handler ---------------------------------------
    handler = TOOL_DISPATCH.get(result.action)
    if handler is None:
        logger.warning("No handler for action %r — triggering fallback.", result.action)
        mock_fallback_prompt()
        return

    handler(result.filled_args)
